import React, { useState, useEffect } from 'react';
import { useHistory } from 'react-router-dom';
import { getWaybill } from '../api';
import { isAuthenticated } from '../auth';
import { Container, Row, Col, Card, Form, Button, Table } from 'react-bootstrap';
import logger from '../styles/loadingBtn.gif'
import NavComp from './Navigation'

function WaybillHistory() {
  const user = JSON.parse(localStorage.getItem('data'));
  console.log("HERERRRRR")
  const [waybillHistory, setWaybillHistory] = useState([]);
  const history = useHistory();

  useEffect(() => {
    const storedToken = localStorage.getItem('token')
    if (!storedToken) {
        history.push('/login')
    }
}, [history])

  useEffect(() => {
    const fetchWaybillHistory = async () => {
      try {
        const response = await getWaybill();
        setWaybillHistory(response);
      } catch (error) {
        console.error(error);
      }
    };

    fetchWaybillHistory();
  }, []);

  const handleRowClick = (code) => {
    history.push(`/waybill/view/${code}`);
  };

  return (
    <div>
      <NavComp user={user} />
      <Container>
        <h3>Waybill History</h3>
        <Table striped bordered hover>
          <thead>
            <tr>
              <th>Waybill No</th>
              <th>Driver's Name</th>
              <th>Plate Number</th>
              <th>Generated By</th>
            </tr>
          </thead>
          <tbody>
            {waybillHistory?.map((waybill) => (
              <tr key={waybill.code} onClick={() => handleRowClick(waybill.code)}>
                <td>{waybill.waybillNumber.toString().padStart(6, '0')}</td>
                <td>{waybill.firstName} {waybill.lastName}</td>
                <td>{waybill?.vehicleNumber && waybill.vehicleNumber.toUpperCase()}</td>
                <td>{waybill.creator}</td>
                
              </tr>
            ))}
          </tbody>
        </Table>
      </Container>
    </div>
  );
}

export default WaybillHistory;
